
language: node_js
node_js:
  - 12
branches:
  only:
    - master
cache:
  npm: true
script:
  # First, transform OpenAPI to Markdown
  - npm i -g widdershins
  - widdershins ./openapi.yaml -o output.md
  # Then push it to the docs repo
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - git clone https://github.com/apidocsfordevs/pantheon-docs.git
  - cd pantheon-docs
  - cp ../output.md ./docs/payments.md
  - git add ./docs/payments.md
  - git commit -m "Built docs via Travis CI"
  - git push